---

# Install K3S Stack

- name: provisioning resources
  hosts: local
  gather_facts: yes
  become: no

  tasks:
#    - name: Install LongHorn
#      k8s:
#        state: present
#        src: longhorn-v1.3.2.yaml

    - name: Add longhorn chart repo
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "https://charts.longhorn.io"

    - name: Deploy latest version of longhorn chart
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        create_namespace: true
        update_repo_cache: true
      run_once: true

 


