---
# tasks file for node

- name: Install K3S as additional master node
  shell: 'curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} K3S_TOKEN={{ k3s_token }} sh -s server --server https://{{ MASTER_IP }}:6443 --node-external-ip={{ ansible_eth0.ipv4.address }}  --node-ip={{ ansible_eth1.ipv4.address }} --advertise-address={{ ansible_eth1.ipv4.address }} --flannel-iface=eth1'